#
# Copyright © 2014 Cask Data, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.
#

language: java

jdk:
  - oraclejdk7
## Commenting it out by @ajainarayanan @gaarf as sauce doesn't taste good.

env:
  global:
    - COOPR_SERVER_HOME=`pwd`/coopr-server
    - COOPR_SERVER_URI=http://127.0.0.1:55054
    - COOPR_USE_DUMMY_PROVISIONER=true
    - SELENIUM_HOST=hub.browserstack.com
    - SELENIUM_PORT=80
    - BS_AUTOMATE_PROJECT="$TRAVIS_REPO_SLUG"
    - BS_AUTOMATE_BUILD="Travis build No. $TRAVIS_BUILD_NUMBER for $TRAVIS_REPO_SLUG"
    - secure: "e0hGcYelU0lGp4K/+wamBrdyhIoQAbcU6EMvfZia+wo/r0lZKOdz8t3l5Drldztg8nx0bqW4gp8GPa23D+RpHHc9GZlarmjCZp91QS6gK5+3dSINWy70FtmMGSvacKPYahZY0r1UZrb6uFHCH2g5S9F8Pd2YTGQ5FmOwbx6q1VE="
    - secure: "d9LUka6j4TeGlKzjNrNOHPpHtjj4zW85n6vmRbIlJ8N+8nC9tI5418x8KO0Y4fA0pSSCJ3ge2wNoI0LR5+mmEBpPP0Z6EEF5hKJSPWxRFM40HHZrgnB9ZIghgIDOO0FRtG+yr6pnBlBidoufE7wDhQwuylnS8Vf8GEQt8RrhKJ8="
    matrix:
      - SELENIUM_PLATFORM=LINUX SELENIUM_BROWSER=CHROME SELENIUM_VERSION=9

branches:
  only:
    - develop
    - /^feature\/.*$/
    - /^hotfix\/.*$/
    - /^release\/.*$/

# before_install:
#   - 'export CHROME_BIN=chromium-browser'
#   - 'export DISPLAY=:99.0'
#   - 'sh -e /etc/init.d/xvfb start'

before_script:
  - 'cd coopr-ngui && npm run build'
  - 'npm start > /dev/null &'
  - 'cd ..'
  - 'if [ -n "$SAUCE_ACCESS_KEY" ]; then cd coopr-server; fi'
  - 'if [ -n "$SAUCE_ACCESS_KEY" ]; then mvn clean package assembly:single -DskipTests; fi'
  - 'if [ -n "$SAUCE_ACCESS_KEY" ]; then cd ..; fi'
  - 'if [ -n "$SAUCE_ACCESS_KEY" ]; then java -cp coopr-server/target/*:coopr-e2e/config co.cask.coopr.runtime.ServerMain; fi >/dev/null 2>&1 &'
  - 'if [ -n "$SAUCE_ACCESS_KEY" ]; then java -cp coopr-server/target/*:coopr-e2e/config co.cask.coopr.runtime.MockProvisionerMain -p 55054; fi >/dev/null 2>&1 &'
  - 'sleep 30' # give servers generous time to start
  - 'if [ -n "$SAUCE_ACCESS_KEY" ]; then cd coopr-e2e; fi'
  - 'if [ -n "$SAUCE_ACCESS_KEY" ]; then npm run build; fi'
  - 'if [ -n "$SAUCE_ACCESS_KEY" ]; then cd ..; fi'
  - 'if [ -n "$SAUCE_ACCESS_KEY" ]; then bash coopr-server/templates/mock/load-mock.sh; fi'

script:
  - 'cd coopr-ngui'
  # - 'node ./node_modules/gulp/bin/gulp.js jshint'
  # - 'npm run test-single-run'
  - 'if [ -n "$SAUCE_ACCESS_KEY" ]; then cd ../coopr-e2e; fi'
  - 'if [ -n "$SAUCE_ACCESS_KEY" ]; then npm run protractor; fi'
  # - 'cd ..'
  # - 'mvn test'
