#
# Copyright © 2014 Cask Data, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.
#

language: java

jdk:
  - oraclejdk7

env:
  global:
    - secure: "XRVVni+G1G2bvSjd65dAJzDCccF/FyfeD8DrkIo9TU0at6eas+wj/BIxlGlE6haMAomRwku8zkCIDawDHiGyNUBxQfM5I+9bhodM7RqIc0zUXFFtsD0uEhdq+XA7JuzRou5bvZoI2ZnKovLER3QIyNpkjmWJcZ1F7kafjm67aBo="
    - secure: "U4DMqL41wYrH63a7Vwst421tTs/P9GeNwtHmkSM0u4ZbEzKcjLuHbqbd4e6rKKIUqaAE282H4qYk3ESQY8wWJ9xPwVFw2jfJPrTeeed6DjT45bpHlUMUDvw4RrG5YqXwYaiw1wD97XMUC1I4YWSdhdlIU1ucn/PRR3mdO30ocZw="
    - COOPR_SERVER_HOME=`pwd`/coopr-server
    - COOPR_SERVER_URI=http://127.0.0.1:55054
    - COOPR_USE_DUMMY_PROVISIONER=true
    - SELENIUM_HOST=hub.browserstack.com
    - SELENIUM_PORT=80
    - BS_AUTOMATE_PROJECT="$TRAVIS_REPO_SLUG"
    - BS_AUTOMATE_BUILD="Travis build No. $TRAVIS_BUILD_NUMBER for $TRAVIS_REPO_SLUG"

branches:
  only:
    - develop
    - /^feature\/.*$/
    - /^hotfix\/.*$/
    - /^release\/.*$/

before_install:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'

before_script:
  - 'cd coopr-ngui && npm run build'
  - 'npm start > /dev/null &'
  - 'cd ..'

install:
  - 'cd coopr-provisioner && bundle install --without integration'
  - 'cd ..'

script:
  - 'cd coopr-provisioner && bundle exec rake'
  - 'cd ..'
  - 'cd coopr-ngui'
  - 'node ./node_modules/gulp/bin/gulp.js jshint'
  - 'npm run test-single-run'
  - 'cd ..'
  - 'mvn test'
