
language: node_js
node_js:
  - 0.10

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm run build"

script:
  - "npm run jshint"
  - "npm run test-single-run"
  - "npm run protractor"
