inherit_from: .rubocop_todo.yml
AllCops:
  Exclude:
    - worker/plugins/automators/chef_solo_automator/chef_solo_automator/cookbooks/**/*
# Uncomment to not test any plugin code
#    - worker/plugins/**/*
